# This file automatically generated by vpl
# please do not modify
set local_dir ".local"
source -notrace "$local_dir/ocl_util.tcl"
source -notrace "$local_dir/platform.tcl"
source -notrace "$local_dir/debug_profile.tcl"
source -notrace "$local_dir/debug_profile_util.tcl"
source -notrace "$local_dir/debug_hw.tcl"
source -notrace "$local_dir/profile.tcl"
source -notrace "$local_dir/hw_emu_common_util.tcl"

namespace eval ::optrace {
  variable script "ipirun.tcl"
  variable category "vpl"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "ipirun" START { ROLLUP_0 }
set vivado_error_file "vivado_error.txt"
set vivado_warn_file "vivado_warning.txt"
set vivado_output_dir "output"
set output_dir "output"
set vpl_output_dir "/home/jacksoncd/solver-acceleration/linear_solver_lib/solver/L2/tests/gelinearsolver/build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/link/int"
set input_dir "input"
set steps_log "../../link.steps.log"
set kernel_ip_dirs {
  {/home/jacksoncd/solver-acceleration/linear_solver_lib/solver/L2/tests/gelinearsolver/build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/link/int/xo/ip_repo/xilinx_com_hls_kernel_gelinearsolver_0_1_0}}
set install_ip_cache "/tools/Xilinx/Vitis/2020.1/data/cache/xilinx"


set impl_xdc [dict create \
];

set dict_impl [dict create \
  file_path ".local/hw_platform/tcl_hooks/impl.xdc" \
  used_in "implementation" \
  processing_order "NORMAL" \
];

set synth_xdc [dict create \
  impl ${dict_impl} \
];

set utilization [dict create \
  luts                   -1 \
  brams                  -1 \
  registers              -1 \
  dsps                   -1 \
];


set bus_sp_tags [list]
set bus_sp_indeces [list]

lappend bus_sp_tags HBM_MEM00 HBM
lappend bus_sp_indeces HBM_MEM00 0
lappend bus_sp_tags HBM_MEM01 HBM
lappend bus_sp_indeces HBM_MEM01 1
lappend bus_sp_tags HBM_MEM02 HBM
lappend bus_sp_indeces HBM_MEM02 2
lappend bus_sp_tags HBM_MEM03 HBM
lappend bus_sp_indeces HBM_MEM03 3
lappend bus_sp_tags HBM_MEM04 HBM
lappend bus_sp_indeces HBM_MEM04 4
lappend bus_sp_tags HBM_MEM05 HBM
lappend bus_sp_indeces HBM_MEM05 5
lappend bus_sp_tags HBM_MEM06 HBM
lappend bus_sp_indeces HBM_MEM06 6
lappend bus_sp_tags HBM_MEM07 HBM
lappend bus_sp_indeces HBM_MEM07 7
lappend bus_sp_tags HBM_MEM08 HBM
lappend bus_sp_indeces HBM_MEM08 8
lappend bus_sp_tags HBM_MEM09 HBM
lappend bus_sp_indeces HBM_MEM09 9
lappend bus_sp_tags HBM_MEM10 HBM
lappend bus_sp_indeces HBM_MEM10 10
lappend bus_sp_tags HBM_MEM11 HBM
lappend bus_sp_indeces HBM_MEM11 11
lappend bus_sp_tags HBM_MEM12 HBM
lappend bus_sp_indeces HBM_MEM12 12
lappend bus_sp_tags HBM_MEM13 HBM
lappend bus_sp_indeces HBM_MEM13 13
lappend bus_sp_tags HBM_MEM14 HBM
lappend bus_sp_indeces HBM_MEM14 14
lappend bus_sp_tags HBM_MEM15 HBM
lappend bus_sp_indeces HBM_MEM15 15
lappend bus_sp_tags HBM_MEM16 HBM
lappend bus_sp_indeces HBM_MEM16 16
lappend bus_sp_tags HBM_MEM17 HBM
lappend bus_sp_indeces HBM_MEM17 17
lappend bus_sp_tags HBM_MEM18 HBM
lappend bus_sp_indeces HBM_MEM18 18
lappend bus_sp_tags HBM_MEM19 HBM
lappend bus_sp_indeces HBM_MEM19 19
lappend bus_sp_tags HBM_MEM20 HBM
lappend bus_sp_indeces HBM_MEM20 20
lappend bus_sp_tags HBM_MEM21 HBM
lappend bus_sp_indeces HBM_MEM21 21
lappend bus_sp_tags HBM_MEM22 HBM
lappend bus_sp_indeces HBM_MEM22 22
lappend bus_sp_tags HBM_MEM23 HBM
lappend bus_sp_indeces HBM_MEM23 23
lappend bus_sp_tags HBM_MEM24 HBM
lappend bus_sp_indeces HBM_MEM24 24
lappend bus_sp_tags HBM_MEM25 HBM
lappend bus_sp_indeces HBM_MEM25 25
lappend bus_sp_tags HBM_MEM26 HBM
lappend bus_sp_indeces HBM_MEM26 26
lappend bus_sp_tags HBM_MEM27 HBM
lappend bus_sp_indeces HBM_MEM27 27
lappend bus_sp_tags HBM_MEM28 HBM
lappend bus_sp_indeces HBM_MEM28 28
lappend bus_sp_tags HBM_MEM29 HBM
lappend bus_sp_indeces HBM_MEM29 29
lappend bus_sp_tags HBM_MEM30 HBM
lappend bus_sp_indeces HBM_MEM30 30
lappend bus_sp_tags HBM_MEM31 HBM
lappend bus_sp_indeces HBM_MEM31 31
lappend bus_sp_tags PLRAM_MEM00 PLRAM
lappend bus_sp_indeces PLRAM_MEM00 0
lappend bus_sp_tags PLRAM_MEM01 PLRAM
lappend bus_sp_indeces PLRAM_MEM01 1
lappend bus_sp_tags PLRAM_MEM02 PLRAM
lappend bus_sp_indeces PLRAM_MEM02 2
lappend bus_sp_tags PLRAM_MEM03 PLRAM
lappend bus_sp_indeces PLRAM_MEM03 3

set hw_platform_info [dict create \
  hw_platform_dir              ".local/hw_platform" \
  hw_platform_file             "/opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/hw/hw.xsa" \
  hw_platform_part             "xcu50-fsvh2104-2-e" \
  hw_platform_vbnv             "xilinx:u50:gen3x16_xdma:201920.3" \
  bb_locked_dcp                ".local/hw_platform/hw_bb_locked.dcp" \
  hw_platform_uses_pr           true \
  uses_pr_shell_dcp             false \
  pr_shell_dcp                 "" \
  hw_platform_state            "impl" \
  ocl_region                   "level0_i/ulp" \
  dr_bd_name                   "ulp.bd" \
  utilization                   $utilization \
  hw_platform_dr_bd            ".local/hw_platform/emu/emu.bd" \
  hw_platform_rebuild_tcl      "" \
  pre_sys_link_tcl               ".local/hw_platform/emu/dynamic_prelink.tcl" \
  post_sys_link_tcl              ".local/hw_platform/emu/dynamic_postlink.tcl" \
  pre_sys_link_overlay_tcl       "" \
  post_sys_link_overlay_tcl      "" \
  post_debug_profile_overlay_tcl "" \
  pre_create_project_tcl         "" \
  user_pre_create_project_tcl    "" \
  user_pre_sys_link_tcl          "" \
  user_post_sys_link_tcl         "" \
  user_pre_sys_link_overlay_tcl  "" \
  user_post_sys_link_overlay_tcl "" \
  user_post_debug_profile_overlay_tcl "" \
  synth_xdc                     $synth_xdc \
  impl_xdc                      $impl_xdc \
  hw_platform_ip_repo          ".local/hw_platform/iprepo" \
  hw_platform_ip_cache         ".local/hw_platform/ipcache" \
  emu_user_ip_repo             ".local/hw_platform/emu/user_ip_repo" \
  emu_src_dir                  "" \
  emu_pfm_metadata_version     "Legacy" \
  hw_platform_board_repo       ".local/hw_platform/board" \
  hw_platform_bconn_locked      {} \
  hw_platform_bconn_unlocked    {} \
  hw_platform_board_part       "xilinx.com:au50:part0:1.0" \
  link_output_format           "bitstream" \
  xpfm_file                    "/opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm" \
  bus_sp_tags                   $bus_sp_tags \
  bus_sp_indeces                $bus_sp_indeces\
  design_intent_server_managed  true \
  design_intent_external_host   true \
  design_intent_datacenter      true \
  design_intent_embedded        false \
];


set config_info [dict create \
  proj_name                "prj" \
  emu_proj_name            "prj" \
  design_name              "dr" \
  out_partial_bitstream    "$vpl_output_dir/partial.bit" \
  out_partial_pdi          "$vpl_output_dir/partial.pdi" \
  out_partial_clear_bit    "$vpl_output_dir/partial_clear.bit" \
  out_full_bitstream       "$vpl_output_dir/system.bit" \
  out_full_pdi             "$vpl_output_dir/system.pdi" \
  out_mcs                  "$vpl_output_dir/system.mcs" \
  out_primary_mcs          "$vpl_output_dir/system_primary.mcs" \
  out_secondary_mcs        "$vpl_output_dir/system_secondary.mcs" \
  enable_dont_partition     true \
  enable_util_report        true \
  utilization_threshold     0.8 \
  generate_script_only      false \
  run_script_map_file      "" \
  clbinary_name            "kernel_gelinearsolver" \
  kernels                  "kernel_gelinearsolver_0" \
  steps_log                 $steps_log \
  impl_from_step           "" \
  impl_to_step             "" \
  num_jobs                  8 \
  lsf_string               {} \
  optimize_level            0 \
  is_hw_emu                 true \
  user_ip_repo              {} \
  kernel_ip_dirs            $kernel_ip_dirs \
  no_hw_platform_ip_cache   false \
  no_install_ip_cache       false \
  install_ip_cache          $install_ip_cache \
  no_ip_cache               false \
  remote_ip_cache          "/home/jacksoncd/solver-acceleration/linear_solver_lib/solver/L2/tests/gelinearsolver/.ipcache" \
  user_board_repo           {} \
  user_bconn                {} \
  dr_bd_tcl                ".local/dr.bd.tcl" \
  webtalk_flag             "Vitis" \
  encrypt_impl_dcp          false \
  encrypt_key_file         "" \
  enable_pr_verify          false \
  return_pre_sys_link_tcl   false \
  return_pre_synth          false \
  return_post_synth         false \
  return_pre_impl           false \
  disable_run_configs       false \
  protocol_checker          false \
  hw_emu_profiling          true \
  scripts_dir              "scripts" \
  output_dir               "$output_dir" \
  vivado_output_dir        "$vivado_output_dir" \
  vpl_output_dir           "$vpl_output_dir" \
  input_dir                "$input_dir" \
  local_dir                "$local_dir" \
  tclhook_prefix           "_vpl" \
  partition_def            "my_pd" \
  reconfig_module          "my_rm" \
  pr_config_name           "config_1" \
  failfast_config          {} \
  enable_explicit_emu_data  false \
  aie_archive_file         "/home/jacksoncd/solver-acceleration/linear_solver_lib/solver/L2/tests/gelinearsolver/build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/link/int/system.aieprj" \
  system_dpa_enabled       "1" \
  is_hw_export              false \
  fixed_xsa                "vpl_gen_fixed.xsa" \
  enable_smart_xplore      "0" \
  smart_xplore_strategies  "" \
];


set kernel_clock_freqs [dict create \
];

set dict_hbm_aclk [dict create \
  is_user_set false \
  clk_id "" \
  freq_orig 450 \
  freq 450 \
];
set system_clock_freqs [dict create \
  hbm_aclk $dict_hbm_aclk \
];

set clk_info [dict create \
  kernel_clock_freqs         $kernel_clock_freqs \
  system_clock_freqs         $system_clock_freqs \
  worst_negative_slack      0 \
  max_frequency             650 \
  min_frequency             10 \
  error_on_hold_violation   true \
  skip_timing_and_scaling   false \
  enable_auto_freq_scale    true \
];

set dict_debug [dict create \
  version "1.0" \
];
dict set dict_debug kernel_debug false
set dict_profile [dict create \
  NAME profile_monitors \
  FIFO "8192" \
  DATA [list] \
  STALL [list] \
  EXEC [list] \
  AIE_TRACE_EVENT_PACKET_RATE "100" \
  AIE_TRACE_PROFILE_STREAMS "0" \
];
set debug_profile_info [dict create debug $dict_debug profile $dict_profile]

source [dict get $config_info scripts_dir]/_vivado_params.tcl


OPTRACE "ipirun" END { }

