catch {::common::set_param -quiet hls.xocc.mode csynth};
catch {::common::set_param -quiet hls.enable_scout_hidden_option_error false};
# 
# Hls run script generated by the compiler
# 

set vpp_optimize_level 0
open_project kernel_gelinearsolver_0
set_top kernel_gelinearsolver_0
add_files "/home/jacksoncd/solver-acceleration/linear_solver_lib/solver/L2/tests/gelinearsolver/kernel_gelinearsolver.cpp" -cflags " -I /home/jacksoncd/solver-acceleration/linear_solver_lib/solver/L2/tests/gelinearsolver -I /home/jacksoncd/solver-acceleration/linear_solver_lib/solver/L2/include -I /home/jacksoncd/solver-acceleration/linear_solver_lib/solver/ext -I /home/jacksoncd/solver-acceleration/linear_solver_lib/solver/L2/tests/gelinearsolver "
open_solution -flow_target vitis solution
set_part xcu50-fsvh2104-2-e
create_clock -period 300.000000MHz -name default
config_export -vivado_optimization_level $vpp_optimize_level
config_dataflow -strict_mode warning
set_clock_uncertainty 27.000000%
config_rtl -m_axi_conservative_mode=1
config_interface -m_axi_addr64
config_interface -default_slave_interface s_axilite
config_export -format ip_catalog -ipname kernel_gelinearsolver_0
catch {::common::set_param -quiet hls.enable_synthesis_check_sw_only true};
csynth_design -synthesis_check
close_project
puts "HLS completed successfully"
exit
